apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
          - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: mongodb-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdr
  labels:
    app: mdr
spec:
  selector:
    matchLabels:
      run: mdr
  replicas: 1
  template:
    metadata:
      labels:
        run: mdr
    spec:
      containers:
      - name: mdr
        image: mdr:v1
        ports:
        - containerPort: 8081
        # env:
        #   - name: ME_CONFIG_MONGODB_SERVER
        #     valueFrom:
        #       configMapKeyRef:
        #         name: mongodb-configmap
        #         key: database_url